name: Log Website Visit

on:
  workflow_dispatch:
    inputs:
      visitor:
        description: 'Visitor Information'
        required: false

jobs:
  log-visit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update CSV
        run: |
          echo "$(date +'%Y-%m-%d %H:%M:%S'), ${{ github.event.inputs.visitor }}" >> visit_log.csv

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add visit_log.csv
          git commit -m "Log visit"
          git push
